version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: MajesticCup
    ports:
      - "27017:27017"
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latestcon
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_DATABASE: MajesticCup
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - app-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongo:27017/MajesticCup
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
